# Generated by Django 5.1.6 on 2025-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_email_verified_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('staff', 'Staff')], default='user', max_length=10),
        ),
    ]
