# Generated by Django 5.1.6 on 2025-11-28 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'staff'}, related_name='courses_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
